# Dependencies
#markdown:            redcarpet
highlighter:         pygments
markdown:            kramdown

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
name:                Avan's Blog
title:               avan
tagline:             'is scribbling about his research life'
description:         Notes on medical imaging, statistics and coding from Avan's research life
url:                 http://avansp.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Avan Suinesiaputra
  url:               http://avansp.github.io
  email:             avansp@gmail.com
  github:            avansp
  disqus-shortname:  Avan
  avatar:            bio-photo.jpg
  googleplus:        104904508082327305960

# Custom vars
404image:            homerMRI.jpg
