# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Avan's Notes
email: 
description: > # this means to ignore newlines until "baseurl:"
  On statistical shape, cardiac modelling, medical image analysis,
  literate programming, and some amusing things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://avansp.github.io" # the base hostname & protocol for your site
twitter_username: asui085
github_username:  avansp

# Build settings
markdown: kramdown
